CREATE TABLE UTENTE(
    PERSONA_ID INT PRIMARY KEY NOT NUll IDENTITY(1,1),
    NOME VARCHAR (255),
    COGNOME VARCHAR(255),
    PAROLA_SEGRETA VARCHAR(855),
    DATA_DI_NASCITA DATE,
    GENERE_PREFERITO VARCHAR(255)
);